name: flutter_app
description: A new Flutter application.

# 标明版本号，例如3.0.0+5
# 3.0.0 用于展示给用户
# 5 用于实际判断版本号
version: 3.0.3+8

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  awesome_dialog: ^1.1.3
  amap_location: ^0.2.0

  cupertino_icons: ^0.1.3
  cached_network_image: ^2.2.0+1
  dio: 3.0.9
  extended_image: ^0.9.0
  flutter_launcher_icons: ^0.7.5
  flutter_local_notifications: ^2.0.0  # iOS todo
  flutter_spinkit: ^4.1.2+1
  flutter_webview_plugin: ^0.3.11
  flutter_icons: ^1.1.0
  flutter_swiper: ^1.1.6
  flutter_xupdate: ^0.0.3

  flustars: ^0.3.3
  fluwx: ^2.3.0
  fl_chart: ^0.10.1
  image_picker: ^0.6.7+4
  package_info: ^0.4.1
  permission_handler: ^5.0.1+1
  shared_preferences: ^0.5.8
  share: ^0.6.4+3
#  sqflite: ^1.3.1
  sy_flutter_qiniu_storage: ^0.2.1
  toast: ^0.1.5
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/imgs/logo.png"
  image_path_ios: "assets/imgs/logo.png"
  android: "logo"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: IconFont
      fonts:
        - asset: assets/fonts/iconfont.ttf

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/imgs/core/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
flutter_intl:
  enabled: true
