name: flutter_app
description: A new Flutter application.

# 标明版本号，例如3.0.0+5
# 3.0.0 用于展示给用户
# 5 用于实际判断版本号
version: 3.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: 3.0.9
  shared_preferences: ^0.5.6+3
  cupertino_icons: ^0.1.3
  english_words: ^3.1.0
  flutter_webview_plugin: ^0.3.10+1
  flutter_icons: ^1.0.0+1
  flustars: ^0.2.6+1
  awesome_dialog: ^0.1.3
  flutter_beautiful_popup: ^1.5.0

  flutter_spinkit: ^4.1.2+1
  sqflite: ^1.3.0
  path_provider: ^1.6.5

  toast: ^0.1.5
  image_picker: ^0.6.4
  flutter_swiper: ^1.1.6
  package_info: ^0.4.0+14
  share: ^0.6.3+6
  fl_chart: ^0.8.7
  url_launcher: ^5.4.2
  cached_network_image: ^2.0.0
  sy_flutter_qiniu_storage: ^0.1.4
  umeng_analytics_plugin: ^1.0.2
  fluwx: ^2.0.2
  flutter_launcher_icons: ^0.7.4
  flutter_xupdate: ^0.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/imgs/logo.jpg"
  image_path_ios: "assets/imgs/logo.jpg"
  android: true
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
#  adaptive_icon_background: "assets/images/christmas-background.png" # only available for Android 8.0 devices and above
#  adaptive_icon_foreground: "assets/images/icon-foreground-432x432.png" # only available for Android 8.0 devices and above


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/imgs/
    - assets/imgs/core/
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
flutter_intl:
  enabled: true
